language: java
sudo: false # faster builds
script:
 - mvn test
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
 - oraclejdk8

 deploy:
  provider: releases
  api_key: $githubToken
  file_glob: true
  file: target/processadorplanilha-*.jar
  skip_cleanup: true
  on:
    tags: true